openapi: 3.0.4
info:
  title: WMATA Accessibility API
  description: JHU Intro Python Module 7 Assignment - WMATA Accessibility
  version: 1.0.0
paths:
  /incidents/{machine_type}:
    get:
      tags:
        - Incidents 
      summary: Get a list of machine incidents by machine
      parameters:
        - name: machine_type
          in: paths
          description: Machine type
          required: true
          scheme:
            type: string
      responses:
        '200':
          description: Request Successfully Completed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Machine' 
components:
  schemas:
    Machine:
      type: object
      properties:
        StationCode:
          type: string
          example: A11
        StationName:
          type: string
          example: Grosvenor-Strathmore
        UnitName:
          type: string
          example: A11X01
        UnitType:
          type: string
          example: ELEVATOR
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/zakiyawilliams617org/WMATA_Accessibility_API/1.0.0